import string
import operator
alphabet = string.ascii_uppercase

msg = """IHGFEDC BAJIJ KIL CUAHMBI NI OKDKFCBIBD I OFLFPABUNCD GNAKYJD
LFGNFK CEIHM OKFOEANI UCA NAJOAKIJABNBD KAHD VZBICIJ ZA BI NFJ
BIZFKBAJ OKDGEILV U GICIKBFV HEFCAGAJ I JDUFV GFPEDM BAHF SA EZA BI
BAJ IUOFB OKDPEDZBA VGIZIN SIGYJ HEFCAGAJ SA UINVKBDB LFGNFK CEIHM
UD NFNDZ KFZLAEDE EDLD OFLEA NFMF SIG UA HMFCISD C OFEFOKIZLBA
GICIKBA JISDED OKAL UAPFV JDUV GFPEDM OKALUNICNA UD EVXVUBD GICIKBV
ZI BALAEBDMF FLOFEALBA CABGV SA GKIUBY LAB I MFUNV C GICIKBA
SA JIEF VZ SUNA UA BIUBDLIED OKAHANED SUNA CUAHMBY BFCDBY I NAL
SUNA UA OFMFLEBA FOKAED C JAGGAJ PFXV I ZIJYUEABA UA LDCINA BI JDUV
GFPEDM BVLI UA OFJIEV KFZEAZI LF CUAHM GFVNV GICIKBY I NV UA NALY
JI VGIZIN LF GNAKA UGVODBY EDLD OFLEA NAFKDA LFGNFKI CEIHMI OINKDNA
SUNAED OKY HEFCAGAJ PAZ QIBNIZDA PAZ NFVMY OF LYBIJDHA I PAZ UJYUEV
OKF MVJFK PVLANA UA BI NY GFPEDMY LDCIN NVOA I PAZJYUEABGFCDNA
NKAPI IZ LF OFEALBA I OIG UA ZCALBANA I OVSLANA G FPALV JIJ LVCFLBA
OFLAZKABD ZA LF NANF OKCA UGVODBY ZIKIZVSA LFGNFK CEIHM NIGA JBA
JYUEDJ ZA BABD C OKICV F MVJFKV I F NA LYBIJDHA BAPVLAJA JEVCDN IEA
NF ZA JD VODKI QIBNIZDD GLYZ CD ZA UA JD OFCALEF UOKICBA""".rstrip()

encoded = [i for i in msg]
decoded = [i for i in msg]

while True:
    cChar = input("Pismeno, ktere chces nahradit: ").rstrip().upper()
    dChar = input("Pismeno, kterym ho chces nahradit: ").rstrip().upper()
    for k in range (0, len(encoded)):
        if encoded[k] == cChar:
            decoded[k] = dChar
    print ("".join(decoded))
